spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrms
    username: postgres
    password: bxa7ikbtBN77E94gCeME
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

